site_name: LLM Agents Hub
site_description: Curated resources on LLM-based agents.
site_url: https://RafiullahOmar.github.io/llm-agents-hub/
repo_url: https://github.com/RafiullahOmar/llm-agents-hub
repo_name: llm-agents-hub

theme:
  name: material

#extra_javascript:
#  - assets/sheet-refresh.js

extra_css:
  - assets/extra.css

theme:
  name: material
  logo: assets/header-logo.png   # or .svg

extra_css:
  - assets/header.css


nav:
  - Home: index.md
  - Taxonomy: taxonomy.md
  - Research Papers: articles.md
  - Benchmarks: benchmarks.md
  - Repos & Frameworks: repos.md
  - Industry Case Studies: case-studies.md
  - Conferences & Workshops: conferences.md
  - Videos & Talks: videos.md
  - Datasets: datasets.md
  - Newsletters: newsletters.md
  
