site_name: Framelab Â· LLM Agents Hub
site_description: Curated resources on LLM-based agents.
site_url: https://RafiullahOmar.github.io/llm-agents-hub/
repo_url: https://github.com/RafiullahOmar/llm-agents-hub
repo_name: llm-agents-hub

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - tables
  - footnotes
  - def_list

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/header-logo1.png
  favicon: assets/favicon.png

extra_css:
  - assets/extra.css
  - assets/header.css
  - assets/home.css
  - assets/newsletters.css
  - assets/banner.css

extra_javascript:
  - assets/newsletters.js

nav:
  - Home: index.md
  - Taxonomy: taxonomy.md
  - Frameworks: frameworks.md
  - Research Papers: articles.md
  - Benchmarks: benchmarks.md
  - Repos: repos.md
  - Industry Case Studies: case-studies.md
  - Conferences & Workshops: conferences.md
  - Videos & Talks: videos.md
  - Datasets: datasets.md
  - Newsletters: newsletters.md

